### PR TITLE
TextAPI 2.0

### PR DESCRIPTION
**Pull request by TheLuca98**
Needs testing before being merged - any help with that would be very appreciated.

The results of the tests, along with issues and feedback can be posted here.

Thanks to everyone in advance. :smiley:

---

Release info: https://github.com/TheLuca98/TextAPI/releases/tag/v1.8.8-R2.0-pre
Branch: https://github.com/TheLuca98/TextAPI/tree/dev

### CODE REVIEW

**Comment by heyimblake** [comment]
Not working for me. Using latest Spigot Server and API versions. Logs and code of command/usage: https://gist.github.com/heyimblake/fcfd020c82599d0612de I'm positive the issue is not in my command, as I added some other code after the above crash and that was fine.

**Comment by TheLuca98** [comment]
@heyimblake That's because you forgot to include TextAPI in your plugin JAR. If you use Maven, there's the Shade plugin. Otherwise, you should be able to do that via your IDE (in IntelliJ it's _Project Structure_ > _Artifacts_).

**Comment by heyimblake** [comment]
@TheLuca98 Sorry for the late response, but that was the issue. It's working fine now, no issues :+1:

**Comment by TheLuca98** [comment]
@heyimblake Okay, thank you! :+1:

**Comment by TheLuca98** [comment]
Testing closed. Thanks to @heyimblake for helping. Merging now.

**Pull request merged**
